config/routes.rb
Rails.application.routes.draw do
  root to: 'animals#index'
  resources :animals, only: [:index, :show, :new, :create]
end

app/models/animal.rb
class Animal < ApplicationRecord
  WHITELIST = ['age', 'name', 'species']
  class << self
    def from_json(entry)
      begin
        Animal.create!(JSON.load(entry.get_input_stream.read).select {|k,v| WHITELIST.include?(k)})
      rescue => e
        warn e.message
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.order('created_at DESC')

      respond_to do |format|
        format.html
        format.zip do
          stringio = Zip::OutputStream.write_buffer do |zio|
            @animals.each do |animal|
              zio.put_next_entry "#{animal.name}-#{animal.id}.json"
              zio.print animal.to_json(only: [:name, :age, :species])

              dec_pdf = render_to_string :pdf => "#{animal.name}-#{animal.id}.pdf", :template => "animals/index.html.erb", :locals => {animal: animal}, :layouts => false
              zio.put_next_entry("#{animal.name}-#{animal.id}.pdf")
              zio << dec_pdf
            end
          end
          stringio.rewind
          binary_data = stringio.sysread
          send_data(binary_data, :type => 'application/zip', :filename => "animals.zip")
        end
      end
      
  end

  # def index
  #   @animals = Animal.order('created_at DESC')
  #   respond_to do |format|
  #     format.html
  #     format.zip do
  #       compressed_filestream = Zip::OutputStream.write_buffer do |zos|
  #         @animals.each do |animal|
  #           zos.put_next_entry "Bio.docx"
  #           zos.print "=====> NAME\n"
  #           zos.print animal.name
  #           zos.print "\n"
  #           zos.print "=====> SPECIES\n"
  #           zos.print animal.species
  #           zos.put_next_entry "#{animal.name}-#{animal.id}.json"
  #           zos.print animal.to_json(only: [:name, :age, :species])
  #         end
  #       end
  #       compressed_filestream.rewind
  #       send_data compressed_filestream.read, filename: "animals.zip"
  #     end
  #   end
  # end

  def show
    @animal = Animal.find_by(id: params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Animal #{@animal.id}",
        page_size: 'A4',
        template: "animals/show.html.erb",
        # layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  def new
    @animal = Animal.new
  end

  def create
    # byebug
    if params[:archive].present?
      Zip::File.open(params[:archive].tempfile) do |zip_file|
        zip_file.glob('*.json').each { |entry| Animal.from_json(entry) }
      end
    elsif params[:animal][:name] && params[:animal][:age] && params[:animal][:species]
      @animal = Animal.create(
        name: params[:animal][:name],
        age: params[:animal][:age],
        species: params[:animal][:species]
      )
    end
    redirect_to root_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'zip'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<h2>Home</h2>
<div>
<%= link_to 'Add!', new_animal_path %> |
<%= link_to 'Download archive', animals_path(format: :zip) %>
</div>
<h3>All Dogs</h3>
<ul>
  <% @animals.each do |animal| %>
    <li>
      <strong>Name:</strong> <%= link_to "#{animal.name}", animal_path(animal.id) %><br>
      <strong>Age:</strong> <%= animal.age %><br>
      <strong>Species:</strong> <%= animal.species %>
    </li>
  <% end %>
</ul>

app/views/animals/new.html.erb
<h1>Add animals</h1>
<h3>Add animals from existing files</h3>
<p>
  Upload a zip archive with JSON files in the following format:<br>
  <code>{name: 'name', age: 1, species: 'species'}</code>
</p>
<%= form_tag animals_path, method: :post, multipart: true do %>
  <%= label_tag 'archive', 'Select archive' %>
  <%= file_field_tag 'archive' %>

  <%= submit_tag 'Add!' %>
<% end %>

<br>
<h3>Create your own Animal</h3>
<%= form_for @animal, :url => { :action => "create" } do |f| %>
  <%= f.label "Name" %><br>
  <%= f.text_field :name %><br>
  <%= f.label "Age" %><br>
  <%= f.number_field :age %><br>
  <%= f.label "Species" %><br>
  <%= f.text_field :species %><br><br>
  <%= submit_tag "Create" %>
<% end %>

app/views/animals/show.html.erb
<h2><%= @animal.name %></h2>
<div>
  <%= link_to 'DOWNLOAD PDF', animal_path(::Animal.find(params[:id]), format: :pdf) %>
</div>
<div>
  <strong>Name:</strong> <%= @animal.name %><br>
  <strong>Age:</strong> <%= @animal.age %><br>
  <strong>Species:</strong> <%= @animal.species %>
</div>

<%= link_to 'Home', animals_path %>

app/views/animals/wait.html.erb
<%= form_tag animals_path, method: :post, multipart: true do %>
  <%= label_tag 'archive', 'Select archive' %>
  <%= file_field_tag 'archive' %>

  <%= submit_tag 'Add!' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zipper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs | Ruby on Rails</title>
  <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
  <%= yield %>
</body>
</html>